# Generated by Django 4.1.5 on 2023-10-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_delete_chats_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.ManyToManyField(to='chat.message'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='chat',
            field=models.ManyToManyField(to='chat.chat'),
        ),
    ]
