# Generated by Django 4.1.5 on 2023-10-23 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_chat_chat_message_inbox_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='inbox',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='chat.inbox'),
            preserve_default=False,
        ),
    ]
