# Generated by Django 4.1.5 on 2023-10-23 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_remove_inbox_chat_chat_inbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='inbox',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.AddField(
            model_name='chat',
            name='inbox',
            field=models.ManyToManyField(to='chat.inbox'),
        ),
        migrations.AddField(
            model_name='chat',
            name='reciever',
            field=models.ManyToManyField(related_name='reciever', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ManyToManyField(related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
